version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
      major:
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
