name: Changeset Check

on:
  pull_request:
    branches:
      - main

jobs:
  changeset-check:
    if: github.head_ref != 'changeset-release/main'
    name: Changeset Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check for changeset
        run: npx changeset status --since=origin/main
